name: 🆕📥 Update Dependency Graph

on:
  push:
    branches:
      - main # default branch of the project

# https://github.com/marketplace/actions/sbt-dependency-submission#unexpected-status-403
permissions:
  contents: write

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
